
import { Customer, Campaign, Reward } from './types';

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+1 (555) 012-3456',
    status: 'Subscribed',
    points: 1250,
    tier: 'Gold',
    joinedDate: 'Jan 2023',
    lastVisit: 'Today, 9:30 AM',
    tags: ['VIP', 'Espresso'],
    avatar: 'https://picsum.photos/seed/john123/100/100',
  },
  {
    id: '2',
    name: 'Sarah Connor',
    email: 'sarah.c@gmail.com',
    phone: '+1 (555) 987-6543',
    status: 'Unsubscribed',
    points: 120,
    tier: 'Bronze',
    joinedDate: 'Mar 2023',
    lastVisit: 'Oct 12, 2023',
    tags: ['Pastries'],
    avatar: 'https://picsum.photos/seed/sarah789/100/100',
  },
  {
    id: '3',
    name: 'Michael Brown',
    email: 'mike.brown@tech.co',
    phone: '+1 (555) 345-6789',
    status: 'Subscribed',
    points: 50,
    tier: 'Bronze',
    joinedDate: 'Yesterday',
    lastVisit: 'Yesterday, 4:15 PM',
    tags: ['New'],
    avatar: 'https://picsum.photos/seed/mike456/100/100',
  },
  {
    id: '4',
    name: 'Emily Chen',
    email: 'emily.c@design.io',
    phone: '+1 (555) 222-3333',
    status: 'Subscribed',
    points: 890,
    tier: 'Silver',
    joinedDate: 'Aug 2023',
    lastVisit: '2 days ago',
    tags: ['VIP', 'Latte'],
    avatar: 'https://picsum.photos/seed/emily999/100/100',
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'c1',
    name: 'Morning Espresso 20% Off',
    channel: 'SMS',
    status: 'Active',
    reach: '1,240 Sent',
    engagementRate: 45,
    ends: 'Ends in 2 days',
    image: 'https://picsum.photos/seed/coffee/200/200',
  },
  {
    id: 'c2',
    name: 'Free Muffin w/ Large Latte',
    channel: 'Email',
    status: 'Scheduled',
    reach: 'Est. 2,100 Reach',
    engagementRate: 0,
    ends: 'Scheduled: Tomorrow, 9 AM',
    image: 'https://picsum.photos/seed/muffin/200/200',
  },
  {
    id: 'c3',
    name: 'Rainy Day Special',
    channel: 'App Push',
    status: 'Completed',
    reach: '850 Sent',
    engagementRate: 62,
    ends: 'Ended yesterday',
    image: 'https://picsum.photos/seed/rainy/200/200',
  },
];

export const MOCK_REWARDS: Reward[] = [
  {
    id: 'r1',
    name: 'Butter Croissant',
    points: 500,
    description: 'Flaky, warm, and freshly baked every morning.',
    status: 'Available',
    image: 'https://picsum.photos/seed/croissant/400/300',
  },
  {
    id: 'r2',
    name: 'Espresso Shot',
    points: 250,
    description: 'A quick pick-me-up for the road.',
    status: 'Available',
    image: 'https://picsum.photos/seed/espresso/400/300',
  },
  {
    id: 'r3',
    name: 'House Blend Beans (1lb)',
    points: 1200,
    description: 'Take the taste of our cafe home with you.',
    status: 'Available',
    image: 'https://picsum.photos/seed/beans/400/300',
  },
  {
    id: 'r4',
    name: 'Free Latte',
    points: 400,
    description: 'Any size latte with choice of milk.',
    status: 'Draft',
    image: 'https://picsum.photos/seed/latte/400/300',
  },
];
